# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nlp}
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["knife"]
  s.date = %q{2010-09-22}
  s.description = %q{Tools for processing polish language. Tokenization, scanning, categorization...}
  s.email = %q{satre@o2.pl}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "dict/liwc",
     "dict/rid",
     "lib/analyzer.rb",
     "lib/category.rb",
     "lib/dictionary.rb",
     "lib/emoticon.rb",
     "lib/inflectable.rb",
     "lib/lemmatizer.rb",
     "lib/liwc_analyzer.rb",
     "lib/liwc_category.rb",
     "lib/meaningable.rb",
     "lib/morfeusz.rb",
     "lib/nlp.rb",
     "lib/rid_analyzer.rb",
     "lib/rid_category.rb",
     "lib/sentence.rb",
     "lib/stdlib/ext/array.rb",
     "lib/stdlib/ext/string.rb",
     "lib/stree.rb",
     "lib/takipi_web_service",
     "lib/takipi_web_service.rb",
     "lib/text.rb",
     "lib/token.rb",
     "lib/token_scanner.rb",
     "lib/word.rb"
  ]
  s.homepage = %q{http://github.com/knife/nlp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Linguistics tools for processing polish language.}
  s.test_files = [
    "test/helper.rb",
     "test/test_nlp.rb",
     "test/word_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

